---
# Helm
addon_helm_version: 3.7

# Metrics server
addon_metric_server_repo_friendly_name: "kubernetes-metrics-server"
addon_metric_server_repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
addon_metric_server_chart_ref: "{{ addon_metric_server_repo_friendly_name }}/metrics-server"
addon_metric_server_chart_version: "3.8.2"
addon_metric_server_release_name: "metrics-server"
addon_metric_server_release_namespace: "kube-system"

# Kubernetes dashboard
addon_kubernetes_dashboard_repo_friendly_name: "kubernetes-dashboard"
addon_kubernetes_dashboard_repo_url: "https://kubernetes.github.io/dashboard/"
addon_kubernetes_dashboard_chart_ref: "{{ addon_kubernetes_dashboard_repo_friendly_name }}/kubernetes-dashboard"
addon_kubernetes_dashboard_chart_version: "5.3.1"
addon_kubernetes_dashboard_release_name: "kubernetes-dashboard"
addon_kubernetes_dashboard_release_namespace: "kube-system"
