---

docker_system_group: root
docker_system_user: root
docker_storage: /dev/xvdb
docker_service_port: 2375
docker_ce_version: 5:19.03.11~3-0~ubuntu-bionic
docker_ce_cli_version: 5:19.03.11~3-0~ubuntu-bionic
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_deb_url: https://download.docker.com/linux/ubuntu
docker_deb_distro: bionic
