---

- name: Installing dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - lvm2

- name: Loading RBD kernel module
  modprobe:
    name: rbd
    state: present

- name: Creating required directories
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ rook_system_group }}"
    owner: "{{ rook_system_user }}"
    mode: 0755
  with_items:
    - "{{ rook_data_dir_host_path }}"

- name: Setup filesystem on rook storage
  filesystem:
    fstype: ext4
    dev: "{{ rook_data_dir_host_disk }}"
    force: no

- name: Mounting storage for persisting cluster's state on all client nodes
  mount:
    dump: 0
    fstab: "/etc/fstab"
    fstype: ext4
    opts: defaults
    passno: 0
    path: "{{ rook_data_dir_host_path }}"
    src: "{{ rook_data_dir_host_disk }}"
    state: mounted

- name: Copying rook-ceph cluster destroy bash script
  template:
    src: "{{ role_path }}/templates/bash-scripts/destroy-rookceph-k8sminion.sh.j2"
    dest: /usr/local/bin/destroy-rookceph-k8sminion.sh
    group: "{{ rook_system_group }}"
    owner: "{{ rook_system_user }}"
    mode: 0755
    force: yes
