---

- name: Collecting only facts from concerned machines
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['storageminion']}}"
  when: install_type == "server"

- name: "Starting setup of {{ install_type }} node(s)"
  include_tasks: "{{ role_path }}/tasks/{{ install_type }}.yml"
