---

- name: Apt update
  apt:
    upgrade: yes
    update_cache: yes

# Enable automated security updates
# Disable all other automatic updates

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - net-tools
      - dnsutils
      - libnss-resolve

- name: Uninstall network-manager package
  apt:
    name: network-manager
    state: absent

# - name: Uninstall resolvconf package
#   apt:
#     name: resolvconf
#     state: absent

# - name: Creating resolv.conf symbolic link
#   file:
#     src: /run/systemd/resolve/resolv.conf
#     dest: /etc/resolv.conf
#     owner: "{{ system_user }}"
#     group: "{{ system_group }}"
#     state: link
#     force: yes
#   changed_when: false

- name: Disable UFW
  ufw:
    state: disabled

- name: Install iptables
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - iptables-persistent
      - netfilter-persistent

- name: Start and Enable netfilter-persistent service
  systemd:
    name: netfilter-persistent
    daemon_reload: no
    enabled: yes
    masked: no
    state: started
    no_block: no

- name: Setup br-netfilter module
  template:
    backup: yes
    dest: /etc/modules-load.d/
    group: "{{ system_group }}"
    owner: "{{ system_user }}"
    mode: 0755
    src: "{{role_path}}/templates/modules-load/bridge.conf"

- name: Load BrNetfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Sysctls configurations
  sysctl:
    name: "{{ item.key }}"
    reload: yes
    state: present
    value: "{{ item.value }}"
  with_items: "{{ var_sysctls }}"

- name: Create /var/log/journal directory
  file:
    group: systemd-journal
    owner: "{{ system_user }}"
    path: /var/log/journal
    recurse: yes
    state: directory

- name: Set correct permission on /var/log/journal directory
  command: systemd-tmpfiles --create --prefix /var/log/journal
  changed_when: false
  notify: Restart systemd-journald service

- name: Ensure systemd-journald service is enabled and started
  systemd:
    name: systemd-journald
    daemon_reload: no
    enabled: yes
    masked: no
    state: started
    no_block: no

- name: Disable SWAP since kubernetes can't work with swap enabled
  block:
    - name: Disable SWAP
      shell: |
        swapoff -a
      changed_when: false
    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^(.+?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      changed_when: false

- name: Execute handlers
  meta: flush_handlers
