---

network_interface: eth0
kubernetes_cluster_name: valamisdemo
kubernetes_log_dir_path: /var/log/kubernetes
kubernetes_dns_name: "{{ kubernetes_cluster_name }}.local"
kubernetes_service_subnet: "10.96.0.0/12"
kubernetes_pod_subnet: "10.32.0.0/12"
kubernetes_allow_privileged: "false"
kubernetes_anonymous_auth_enabled: "false"
kubernetes_authorization_mode: "Node,RBAC"
kubernetes_events_ttl: "24h0m0s"
kubernetes_cgroup_driver: "systemd"
kubernetes_imagepull_progress_deadline: "60m0s"
kubernetes_serialize_image_pulls: "false"
kubernetes_tls_cipher_suits: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
kubernetes_tls_min_version: "VersionTLS12"
kubernetes_hard_eviction_memory: "200Mi"
kubernetes_kube_reserved_cpu: "200m"
kubernetes_kube_reserved_memory: "500Mi"
kubernetes_kube_reserved_ephimeral_storage: "2Gi"
kubernetes_system_reserved_cpu: "200m"
kubernetes_system_reserved_memory: "500Mi"
kubernetes_kubeproxy_mode: "ipvs"
kubernetes_kubeproxy_ipvs_scheduler: ""
