---

- name: Install dependencies for Kubernetes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - curl
      - bash-completion

- name: Add Apt signing key
  apt_key:
    url: "{{ kubernetes_apt_key_url }}"
    state: present

- name: Add Apt repository
  apt_repository:
    repo: deb {{ kubernetes_deb_url }} {{ kubernetes_deb_distro }} main
    state: present

- name: Create /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: directory
    group: "{{ system_group }}"
    owner: "{{ system_user }}"
    mode: 0755
    recurse: no

- name: Create /etc/bash_completion.d directory
  file:
    path: /etc/bash_completion.d
    state: directory
    group: "{{ system_group }}"
    owner: "{{ system_user }}"
    mode: 0755
    recurse: no

- name: Install dependencies for Kubernetes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "kubelet={{ kubernetes_version }}"
      - "kubeadm={{ kubernetes_version }}"
      - "kubectl={{ kubernetes_version }}"
      - "kubernetes-cni={{ kubernetes_cni_version }}"

- name: Version lock kubernetes packages installed above
  command: apt-mark hold kubelet kubeadm kubectl kubernetes-cni

- name: Setup default config for kubelet service
  copy:
    backup: yes
    dest: /etc/default/kubelet
    group: "{{ system_group }}"
    owner: "{{ system_user }}"
    mode: 0644
    src: "{{ role_path }}/templates/kubelet/etc-default-kubelet"
  notify: Restart kubelet.service

- name: Ensure kubelet.service is enabled and started
  systemd:
    name: kubelet
    daemon-reload: yes
    enabled: yes
    masked: no
    state: started
    no_block: no

- meta: flush_handlers
