
# Firewall (UFW)
- name: Setup firewall
  block:
  - name: Allow access to api-server
    community.general.ufw:
      rule: allow
      direction: in
      interface: "{{ network_interface }}"
      port: '6443'
      proto: tcp
      log: no
      comment: "Kubernetes api-server"
  - name: Allow access to kubelet
    community.general.ufw:
      rule: allow
      direction: in
      interface: "{{ network_interface }}"
      port: '10250'
      proto: tcp
      log: no
      comment: "Kubernetes kubelet"
  - name: Allow access to weave/tcp
    community.general.ufw:
      rule: allow
      direction: in
      interface: "{{ network_interface }}"
      port: '6783'
      proto: tcp
      log: no
      comment: "Weave SDN"
  - name: Allow access to weave/udp
    community.general.ufw:
      rule: allow
      direction: in
      interface: "{{ network_interface }}"
      port: 6783:6784
      proto: udp
      log: no
      comment: "Weave SDN"
  - name: Allow access to weave/sdn
    community.general.ufw:
      rule: allow
      direction: in
      interface: weave
      log: no
      comment: "Weave SDN"
  - name: Allow access to node-exporter
    community.general.ufw:
      rule: allow
      direction: in
      interface: "{{ network_interface }}"
      port: '9100'
      proto: tcp
      log: no
      comment: "Monitoring node-exporter"
  - name: Allow access to multicast traffic
    community.general.ufw:
      rule: allow
      direction: in
      interface: "{{ network_interface }}"
      to_ip: 224.0.0.0/4
      proto: igmp
      log: no
      comment: "Multicast"
  tags:
    - feature/firewall

# Unhold kubernetes packages if required
- name: Unhold kubernetes packages
  command: apt-mark unhold "{{ item }}"
  with_items:
    - kubeadm
    - kubelet
    - kubectl
    - kubernetes-cni
    - conntrack
    - cri-tools
    - socat
  changed_when: false
  when: 'item|string in ansible_facts.packages'

# Install kubernetes common packages and add version lock
- name: Install kubernetes packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "kubeadm={{ kubernetes_version }}"
      - "kubelet={{ kubernetes_version }}"
      - "kubectl={{ kubernetes_version }}"
      - "kubernetes-cni"
  notify: Restart kubelet.service

# Gather package facts
- name: Gather Package facts
  package_facts:
    manager: apt

- name: Hold kubernetes packages
  command: apt-mark hold "{{ item }}"
  with_items:
    - kubeadm
    - kubelet
    - kubectl
    - kubernetes-cni
    - conntrack
    - cri-tools
    - socat
  changed_when: false
  when: 'item|string in ansible_facts.packages'

# Start kubelet
- name: Ensure kubelet.service is enabled and started
  systemd:
    name: kubelet
    daemon-reload: yes
    enabled: yes
    masked: no
    state: started
    no_block: no

- name: Generate kubeadm token
  shell: kubeadm token generate
  register: kubeadmTokenGenerateResult

- name: Add kubeadm configuration
  template:
    src: "{{ role_path }}/templates/master/kubernetes/kubeadm-config.yaml.j2"
    dest: /etc/kubernetes/kubeadm-config.yaml
    group: "{{ kubernetes_system_group }}"
    owner: "{{ kubernetes_system_user }}"
    mode: 0644
  vars:
    kubernetes_kubeadm_token: "{{ kubeadmTokenGenerateResult.stdout }}"

- name: Running preflight checks
  command: "kubeadm init --config /etc/kubernetes/kubeadm-config.yaml phase preflight"
  register: preflightChecks
  ignore_errors: true
  no_log: true

- name: Evaluating preflight checks
  debug:
    msg:
      - "************"
      - "*** INFO ***"
      - "************"
      - "It seems this machine has been already initialized as MASTER, won't be re-initialized in current state. If there is a requirement to re-initialize it as fresh then first reset it with :"
      - "kubeadm reset -f"
  when: preflightChecks.stderr.find('ERROR FileAvailable') != -1 or preflightChecks.stderr.find('ERROR Port') != -1 or preflightChecks.stderr.find('/var/lib/etcd is not empty') != -1

- name: Setup kubernetes master
  command: "kubeadm init --config /etc/kubernetes/kubeadm-config.yaml"
  register: kubeadmInitResult
  ignore_errors: true
  when: preflightChecks is succeeded

- name: Write kubeadm init logs
  block:
    - name: Write kubeadm init stdout result into logs
      copy:
        dest: "{{ kubernetes_log_dir_path }}/kubeadm-init.log"
        content: "{{ kubeadmInitResult.stdout_lines | join('\n') }}"
      when: kubeadmInitResult.stdout_lines is defined
    - name: Write kubeadm init stderr result into logs
      copy:
        dest: "{{ kubernetes_log_dir_path }}/kubeadm-init-error.log"
        content: "{{ kubeadmInitResult.stderr_lines | join('\n') }}"
      when: kubeadmInitResult.stderr_lines is defined

- name: Stop if master setup failed
  fail:
    msg:
      - "**********************"
      - "*** Error detected ***"
      - "**********************"
      - "Kubernetes master setup has failed, please check log files available in {{ kubernetes_log_dir_path }} for more information."
  when: kubeadmInitResult is failed

- name: Add kubectl configuration directory
  file:
    group: "{{ kubernetes_system_group }}"
    owner: "{{ kubernetes_system_user }}"
    path: /root/.kube
    mode: 0700
    recurse: yes
    state: directory

- name: Add kubectl configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    group: "{{ kubernetes_system_group }}"
    owner: "{{ kubernetes_system_user }}"
    mode: 0600
    backup: yes

- name: Validating server startup
  wait_for:
    delay: 5
    timeout: 900
    host: 127.0.0.1
    port: "{{ kubernetes_master_bind_port }}"
    state: started
    msg: 'Server is not ready yet !!'

# Bash completion - kubectl
- name: Add kubectl bash-completion
  shell: "kubectl completion bash > /etc/bash_completion.d/kubectl"
  changed_when: false

# Weave (SDN)
- name: Setup pod network
  shell: kubectl apply -f "{{ kubernetes_pod_netowrk_url }}$(kubectl version | base64 | tr -d '\n')"
  changed_when: false
  tags:
    - feature/weave-sdn

# Kubelet rubber stamp (KCA)
- name: Install kubelet csr approver
  block:
    - name: Checkout KCA (kubelet-csr-approver) repo
      ansible.builtin.git:
        repo: "{{ kubernetes_kca_repo_url }}"
        dest: "{{ kubernetes_kca_repo_checkout_directory }}"
        version: "{{ kubernetes_kca_repo_tag }}"
        force: yes
    - name: Add KRS configuration
      template:
        src: "{{ role_path }}/templates/master/kca/kustomization.yaml.j2"
        dest: "{{ kubernetes_kca_repo_checkout_directory }}/deploy/k8s/kustomization.yaml"
        group: "{{ kubernetes_system_group }}"
        owner: "{{ kubernetes_system_user }}"
        mode: 0644
    - name: Deploy KCA
      shell: "kubectl -n {{ kubernetes_kca_namespace }} kustomize {{ kubernetes_kca_repo_checkout_directory }}/deploy/k8s | kubectl apply -f -"
      changed_when: false
  when: kubernetes_kca_enabled is true or kubernetes_server_tls_bootstrap is true
  tags:
    - feature/kubelet-csr-approver

- name: Execute handlers
  meta: flush_handlers
