
# Unhold kubernetes packages if required
# conntrack cri-tools kubectl kubelet kubernetes-cni socat
- name: Unhold kubernetes packages
  command: apt-mark unhold "{{ item }}"
  with_items:
    - kubeadm
    - kubelet
    - kubernetes-cni
  changed_when: false
  when: 'item|string in ansible_facts.packages'

# Install kubernetes common packages and add version lock
- name: Install kubernetes packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "kubeadm={{ kubernetes_version }}"
      - "kubelet={{ kubernetes_version }}"
      - "kubernetes-cni"
  notify: Restart kubelet.service

- name: Version lock kubernetes packages
  command: apt-mark hold kubeadm kubelet kubernetes-cni
  changed_when: false

# # Configure kubelet
# - name: Add kubelet configuration
#   copy:
#     backup: yes
#     dest: /etc/default/kubelet
#     group: "{{ kubernetes_system_group }}"
#     owner: "{{ kubernetes_system_user }}"
#     mode: 0644
#     src: "{{ role_path }}/templates/kubelet/etc-default-kubelet"
#   notify: Restart kubelet.service

# Start kubelet
- name: Ensure kubelet.service is enabled and started
  systemd:
    name: kubelet
    daemon-reload: yes
    enabled: yes
    masked: no
    state: started
    no_block: no

- name: Execute handlers
  meta: flush_handlers

# Get kubeadm token from master node
- name: Generate kubeadm join command
  shell: kubeadm token create --print-join-command
  register: kubeadmJoinCommand
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: false

# Preflight checks
- name: Running preflight checks
  command: "{{ kubeadmJoinCommand.stdout | regex_replace('join', 'join phase preflight') }}"
  register: preflightChecks
  ignore_errors: true

- name: Validating if node was previously initialized
  debug:
    msg:
      - "************"
      - "*** INFO ***"
      - "************"
      - "It seems this machine has been already initialized, won't be re-initialized in current state. If there is a requirement to re-initialize it as fresh then first reset it with :"
      - "kubeadm reset -f"
  when: preflightChecks.stdout.find('ERROR FileAvailable') != -1 or preflightChecks.stdout.find('ERROR Port') != -1

- name: Setup kubernetes minion
  command: "{{ kubeadmJoinCommand.stdout }}"
  register: kubeadmJoinResult
  ignore_errors: true
  when: preflightChecks is succeeded

- name: Write kubeadm join logs
  block:
    - name: Write kubeadm join stdout result into logs
      copy:
        dest: "{{ kubernetes_log_dir_path }}/kubeadm-join.log"
        content: "{{ kubeadmJoinResult.stdout_lines | join('\n') }}"
      when: kubeadmJoinResult.stdout_lines is defined
    - name: Write kubeadm join stderr result into logs
      copy:
        dest: "{{ kubernetes_log_dir_path }}/kubeadm-join-error.log"
        content: "{{ kubeadmJoinResult.stderr_lines | join('\n') }}"
      when: kubeadmJoinResult.stderr_lines is defined

- name: Skip if play can continue
  fail:
    msg:
      - "**********************"
      - "*** Error detected ***"
      - "**********************"
      - "Kubernetes minion setup has failed, please check log files available in {{ kubernetes_log_dir_path }} for more information."
  when: kubeadmJoinResult is failed
