---

- name: Kubernetes minion installation
  hosts: minion
  remote_user: root
  become: true
  any_errors_fatal: true
  tags:
    - k8s
    - k8s-install
    - k8s-minion-install
  roles:
    - { role: ../roles/kubernetes, node_type: minion, task_type: install }
