---

- name: Kubernetes master upgrade
  hosts: master
  remote_user: root
  become: true
  any_errors_fatal: true
  tags:
    - k8s-upgrade
    - k8s-master-upgrade
  roles:
    - { role: ../roles/kubernetes, node_type: master, task_type: upgrade }
