---

- name: Rook-ceph client setup
  hosts: minion
  remote_user: root
  become: true
  any_errors_fatal: true
  tags:
    - storage
    - storage-clientonly
  roles:
    - { role: ../roles/rook-ceph, install_type: client }
