---
- name: Restart docker.service
  systemd:
    name: docker
    daemon-reload: yes
    state: restarted
    
- name: Allowing enough time for docker to start
  wait_for:
    delay: 100
    timeout: 150
    host: 127.0.0.1
    port: "{{ docker_service_port }}"
    state: started
    msg: "Docker is not ready yet on port {{ docker_service_port }} !!"