---

# Common
network_interface: eth1

# Docker
docker_storage: /dev/xvdb
docker_ce_version: 5:19.03.11~3-0~ubuntu-bionic
docker_ce_cli_version: 5:19.03.11~3-0~ubuntu-bionic
docker_containerdio_version: 1.2.13-2

# Kubernetes
kubernetes_version: 1.17.9-00
kubernetes_cni_version: 0.8.6-00
kubernetes_cluster_name: valpaas

# Rook (Storage)
---
rook_data_dir_host_disk: /dev/xvdc
# Please make sure you maintain the white-spaces as they
# are required for below property "rook_storage_nodes", indentation of 2 is minimum
rook_storage_nodes: |-2
  # List of nodes and devices
      nodes:
      - name: "valpaas24.valamis.local"
        devices:
        - name: xvde
        #- name: xvdg
      - name: "valpaas25.valamis.local"
        devices:
        - name: xvde
        #- name: xvdg
      - name: "valpaas26.valamis.local"
        devices:
        - name: xvde
        #- name: xvdg

# Haproxy (loadbalancer)
haprx_version: "1.8.8-1ubuntu0.10"
