---

- name: Kubernetes master installation
  hosts: master
  remote_user: root
  become: yes
  any_errors_fatal: true
  tags:
    - k8s
    - k8s-master
  roles:
    - { role: kubernetes, node_type: master, task_type: install }
