---

- name: Kubernetes minion upgrade
  hosts: minion
  serial: 2
  remote_user: root
  become: yes
  any_errors_fatal: true
  tags:
    - k8s-upgrade
    - k8s-minion-upgrade
  roles:
    - { role: kubernetes, node_type: minion, task_type: upgrade }
